CREATE TABLE sepatu(
   id              INTEGER  NOT NULL PRIMARY KEY
  ,kategori        VARCHAR(9) NOT NULL
  ,nama            VARCHAR(24) NOT NULL
  ,deskripsi       VARCHAR(335) NOT NULL
  ,harga           INTEGER  NOT NULL
  ,gambar          VARCHAR(28) NOT NULL
  ,berat           VARCHAR(5) NOT NULL
  ,stok            VARCHAR(5) NOT NULL
  ,detail0ukuran   VARCHAR(15) NOT NULL
  ,detail0warna    VARCHAR(29) NOT NULL
);
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310501','Sneakers','Classic Tumble Old Skool','Classic Tumble Old Skool merupakan sepatu skate klasik,ciri khasnya adalah lace-up pada low-top yang menyatu pada bagian atas dengan materi sintetis yang kokoh.',1550000,'Classic-Tumble-Old-Skool.png','410gr','12pcs','40,41,42,43,44','hitam dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310502','Sneakers','SK8-Hi 46 MTE DX','Sk8-Hi 46 MTE DX terbaru mengubah Vans model tinggi legendaris dengan penambahan yang dirancang untuk tiap elemen.',1280000,'SK8-Hi 46 MTE DX.png','390gr','15pcs','40,41,42,43,44','kombinasi');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310503','Sneakers','Authentic Platform 2.0','Vans Authentic Platform 2.0 menggabungkan gaya low-top Vans Authentic dan yang terbaru sekarang secara ikonik ditambahkan dengan bagian atas kanvas yang kokoh.',1045000,'Authentic Platform 2.0.png','400gr','9pcs','40,41,42,43,44','hitam dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310504','Sneakers','SK8-Hi MTE','Sk8-Hi MTE juga memiliki fitur toecaps yang kokoh untuk menjaga ddari keausan. Selain itu kerah sepatu berlapis untuk mendukung performa dan fleksibilitas seepatu vans terbaru ini..',950000,'SK8-Hi MTE.png','430gr','20pcs','40,41,42,43,44','hitam dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310505','Sneakers','Old Skool Platform','The Old Skool Platform menggabungkan sepatu skate klasik dengan material kanvas yang kokoh. Material bagian atas dibangun dari suede, toecaps khas Vans yang tahan dari aus.',1350000,'Old Skool Platform.png','400gr','11pcs','40,41,42,43,44','hitam dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310506','Sneakers','Vans UltraRange 3D','Evolusi dari UltraRange asli, UltraRange 3D mendorong tingkat kenyamanan lebih jauh dengan UltraCush Lite 3D midsole / outsole untuk yang terbaik dalam kenyamanan dan bantalan yang ringan.',1250000,'Vans UltraRange 3D.png','400gr','13pcs','40,41,42,43,44','kombinasi');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310507','Sneakers','Vans Atwood','Canvas Atwood, gaya warisan low-top, menampilkan bagian atas kanvas dijahit ganda untuk daya tahan, lubang tali logam, dan sol luar wafel karet yang khas.',1050000,'Vans Atwood.png','400gr','17pcs','40,41,42,43,44','hitam dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310508','Sneakers','Vans Slip-on','The Canvas Classic Slip-on adalah model sepatu vans yang memiliki bagian atas, kanvas slip-on yang rendah dengan aksen sisi elastis, label bendera Vans dan yang khas yaitu Vans original Waffle Outsole.',1050000,'Vans Slip-on.png','400gr','15pcs','40,41,42,43,44','hitam dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310509','Sneakers','Vans Ave Pro','Menampilkan gabungan DURACAP ™ dan teknologi tanpa jahitan Rapidweld dengan lapisan dalam LuxLiner untuk kesesuaian dan daya tahan optimal, AVE Pro didasarkan pada konstruksi UltimateWaffle ™ baru dari Vans untuk menciptakan sepatu skate terbaik.',1050000,'Vans Ave Pro.png','400gr','15pcs','40,41,42,43,44','hitam,biru dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310510','Sneakers','Vans Old Skool Pro','Menampilkan gabungan DURACAP ™ dan teknologi tanpa jahitan Rapidweld dengan lapisan dalam LuxLiner untuk kesesuaian dan daya tahan optimal, AVE Pro didasarkan pada konstruksi UltimateWaffle ™ baru dari Vans untuk menciptakan sepatu skate terbaik.',1050000,'Vans Old Skool Pro.png','400gr','12pcs','40,41,42,43,44','hitam dan putih');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('310511','Sneakers','Vans UltraRange Hi MTE','Seperti pada versi low-top, UltraRange Hi MTE memberikan estetika yang bersih. Bisa dilihat dari bagian atas kulit, tekstil, dan sintetis dengan detail MTE, lapisan hangat untuk retensi panas, tinta dan lem berbasis air, dan karet tahan lama yang dibalik bersama cetakan wafer lug luar untuk mengurangi lem dan meningkatkan finishing..',1050000,'Vans UltraRange Hi MTE.png','400gr','12pcs','40,41,42,43,44','kombinasi');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('220601','Sandal','Sandal Pria Carvil','Merk carvil menyediakan berbagai macam jenis sandal pria, banyak diminati adalah jenis sandal birkenstock yang elegan, keren, dan juga dapat memberikan kesan yang lebih dewasa.',250000,'Sandal Pria Carvil.jpg','300gr','15pcs','40,41,42,43,44','hitam, biru dan coklat');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('220602','Sandal','Sandal Pria Weinbrenner','sandal yang diperuntukkan untuk aktivitas outdoor, maka sandal dengan merk Weinbrenner biasanya memiliki kekuatan dan ketahanan yang cukup baik.',300000,'Sandal Pria Weinbrenner.jpg','230gr','25pcs','40,41,42,43,44','hitam dan coklat');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('220603','Sandal','Sandal Pria Crocs','Dilengkapi dengan bahan karet anti bakteri dan juga anti slip, sol yang ringan, empuk serta nyaman, Crocs saat ini juga kerap digunakan untuk aktivitas sehari-hari.',150000,'Sandal Pria Crocs.jpg','150gr','18pcs','40,41,42,43,44','hitam, hijau, biru dan coklat');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('220604','Sandal','Sandal Pria Eiger','Sandal-sandal gunung Eiger menawarkan ketangguhan dan juga kenyamanan yang tinggi, sehingga cocok digunakan ketika beraktivitas di permukaan yang cukup terjal sekalipun.',250000,'Sandal Pria Eiger.jpg','200gr','12pcs','40,41,42,43,44','hitam');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('220605','Sandal','Sandal Pria Homyped','Homyped telah memfokuskan perhatiannya untuk memproduksi sandal-sandal yang memiliki kualitas terbaik, dapat menciptakan perasaan nyaman bagi penggunanya, dan juga ramah di kantong masyarakat Indonesia.',380000,'Sandal Pria Homyped.jpg','100gr','5pcs','40,41,42,43,44','hitam');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('110306','Aksesoris','kacamata','kacamata hitam fashion, cocok digunakan di outdor',50000,'kacamata.jpg','30gr','50pcs','dewasa dan anak','hitam');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('110307','Aksesoris','Gelang Fashion','gelang pria keren, dapat digunakan dalam acara formal maupun casual',25000,'gelang.jpg','10gr','30pcs','17-25cm','hitam dan navy');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('110308','Aksesoris','Jam QuickSilver','jam tangan pria keren, dapat digunakan dalam acara formal maupun casual',450000,'jam.jpg','80gr','20pcs','38-44mm','hitam, coklat dan navy');
INSERT INTO sepatu(id,kategori,nama,deskripsi,harga,gambar,berat,stok,detail0ukuran,detail0warna) VALUES ('110309','Aksesoris','Jam G-shock','jam tangan pria keren, dapat digunakan dalam acara formal maupun casual',350000,'jamgshock.jpg','60gr','20pcs','38-44mm','hitam, coklat dan navy');
